[package]
name = "debura-storage"
version.workspace = true
edition.workspace = true

[dependencies]
debura-knowledge = { path = "../debura-knowledge" }
rusqlite.workspace = true
anyhow.workspace = true
chrono.workspace = true
serde_json.workspace = true
tracing.workspace = true

[dev-dependencies]
tempfile = "3"
