/// Filename the compatibility header is written under in
/// `<project>/recovered/include/` and the name every generated header
/// includes it by.
pub const GHIDRA_COMPAT_HEADER_NAME: &str = "ghidra_compat.hpp";

/// Ghidra's decompiler output uses its own placeholder types and a
/// handful of intrinsic-looking helper functions that exist only inside
/// Ghidra itself -- `undefined`, `CONCAT44`, etc. Without declaring them
/// somewhere, every recovered file that so much as mentions an
/// unresolved-type field or return value fails to parse at all. This is
/// a real, verified-by-compiling shim: it was built by actually running
/// g++ against the Snake fixture's recovered output and adding exactly
/// what its errors named (`undefined`/`undefined4`/`undefined8`, `uint`,
/// `ulonglong`, `code`, `CONCAT44`, `__thiscall`) plus `undefined`'s
/// other standard widths and Ghidra's other common short-integer
/// aliases, which are conventional across Ghidra output generally even
/// though this specific binary didn't happen to use them. It is not
/// exhaustive -- Ghidra has other CONCAT/SUB/ZEXT/SEXT combinations for
/// less common width pairings; add them here as real recovered output
/// turns out to need them, the same way this file's initial set was
/// derived.
pub const GHIDRA_COMPAT_HEADER: &str = r#"// Generated by Debura. Declares Ghidra's own placeholder types and
// decompiler intrinsics so recovered output that still contains them
// (an address whose real type Ghidra couldn't infer, a width-combining
// operation the decompiler introduced) at least parses -- it does not
// make the *values* correct, only the syntax valid.
#pragma once
#include <cstdint>
#include <cstdlib>
#include <cstring>
#include <iostream>
#include <sstream>
#include <string>
#include <new>

// A real compile of a MinGW-targeted binary's decompiled output showed
// calls into the C runtime's own startup/threading internals
// (HeapAlloc, EnterCriticalSection, CommandLineToArgvW, ...) and Windows
// types (DWORD, HANDLE, LPVOID, ...) that Debura doesn't try to recover
// as source (a real g++ build already links a working CRT/Win32 layer;
// see debura-knowledge's ClaimClass -- these are excluded from
// *recovery* itself where their own name is recognizable, but a
// statically-linked CRT startup routine can still call them from
// otherwise-ordinary-looking code this shim needs to at least parse).
#ifdef _WIN32
#include <windows.h>
#endif

// SDL2/SDL2_ttf: specific to whatever real binary this shim was last
// verified against (PROJECT.md: this file grows by compiling real
// recovered output and adding exactly what its errors named, the same
// way CONCAT44 below was added) -- a project that doesn't call into SDL
// pays only the include cost, not a hard dependency, since nothing here
// references SDL types by name.
#if __has_include(<SDL.h>)
#include <SDL.h>
#include <SDL_ttf.h>
#endif

// Ghidra's own spelling for the four overridable allocation functions --
// seen in decompiled `new`/`delete` call sites as ordinary function
// calls rather than the real operators, since Ghidra's decompiler
// doesn't render operator-call syntax. Real, observed shape: only the
// non-placement, non-array-vs-scalar-typed forms have shown up so far.
static inline void *operator_new(size_t size) { return ::operator new(size); }
static inline void *operator_new__(size_t size) { return ::operator new[](size); }
static inline void operator_delete(void *ptr) { ::operator delete(ptr); }
static inline void operator_delete__(void *ptr) { ::operator delete[](ptr); }

typedef uint8_t undefined;
typedef uint8_t undefined1;
typedef uint16_t undefined2;
typedef uint32_t undefined3; // Ghidra's own type is 3 bytes; widened here
typedef uint32_t undefined4;
typedef uint64_t undefined5; // Ghidra's own type is 5 bytes; widened here
typedef uint64_t undefined6; // Ghidra's own type is 6 bytes; widened here
typedef uint64_t undefined7; // Ghidra's own type is 7 bytes; widened here
typedef uint64_t undefined8;

typedef unsigned char byte;
typedef signed char sbyte;
typedef unsigned char uchar;
typedef unsigned short ushort;
typedef unsigned short word;
typedef unsigned int uint;
typedef unsigned long long ulonglong;
typedef long long longlong;

// Ghidra's type for "this address holds executable code" -- almost
// always seen only as `code *`, i.e. an opaque function pointer.
typedef void code;

// A real compile showed Ghidra's own signature/decompilation text names
// these STL types bare -- neither `std::`-qualified nor carrying their
// real template arguments (`allocator`, not `std::allocator<char>`;
// `basic_ostream`, not `std::basic_ostream<char, std::char_traits<char>>`)
// -- since Ghidra's type recovery for library templates is partial. Real
// aliases, not placeholders: each names the one instantiation that
// actually shows up in practice (`char`-based, the only one MinGW
// libstdc++ output has needed here so far).
using allocator = std::allocator<char>;
using basic_string = std::basic_string<char, std::char_traits<char>, std::allocator<char>>;
using basic_ostream = std::basic_ostream<char, std::char_traits<char>>;
using basic_stringstream =
    std::basic_stringstream<char, std::char_traits<char>, std::allocator<char>>;

// Calling-convention keyword from Ghidra's x86-32 heritage; x86-64 has
// exactly one calling convention, so this is a no-op here.
#define __thiscall

// Ghidra names a CONCATxy the same way regardless of the specific
// binary: x and y are the byte widths of the high and low halves being
// joined into one wider value.
static inline uint64_t CONCAT44(uint32_t hi, uint32_t lo) {
    return (static_cast<uint64_t>(hi) << 32) | lo;
}
"#;
