/// Filename the compatibility header is written under in
/// `<project>/recovered/include/` and the name every generated header
/// includes it by.
pub const GHIDRA_COMPAT_HEADER_NAME: &str = "ghidra_compat.hpp";

/// Ghidra's decompiler output uses its own placeholder types and a
/// handful of intrinsic-looking helper functions that exist only inside
/// Ghidra itself -- `undefined`, `CONCAT44`, etc. Without declaring them
/// somewhere, every recovered file that so much as mentions an
/// unresolved-type field or return value fails to parse at all. This is
/// a real, verified-by-compiling shim: it was built by actually running
/// g++ against the Snake fixture's recovered output and adding exactly
/// what its errors named (`undefined`/`undefined4`/`undefined8`, `uint`,
/// `ulonglong`, `code`, `CONCAT44`, `__thiscall`) plus `undefined`'s
/// other standard widths and Ghidra's other common short-integer
/// aliases, which are conventional across Ghidra output generally even
/// though this specific binary didn't happen to use them. It is not
/// exhaustive -- Ghidra has other CONCAT/SUB/ZEXT/SEXT combinations for
/// less common width pairings; add them here as real recovered output
/// turns out to need them, the same way this file's initial set was
/// derived.
pub const GHIDRA_COMPAT_HEADER: &str = r#"// Generated by Debura. Declares Ghidra's own placeholder types and
// decompiler intrinsics so recovered output that still contains them
// (an address whose real type Ghidra couldn't infer, a width-combining
// operation the decompiler introduced) at least parses -- it does not
// make the *values* correct, only the syntax valid.
#pragma once
#include <cstdint>

typedef uint8_t undefined;
typedef uint8_t undefined1;
typedef uint16_t undefined2;
typedef uint32_t undefined3; // Ghidra's own type is 3 bytes; widened here
typedef uint32_t undefined4;
typedef uint64_t undefined5; // Ghidra's own type is 5 bytes; widened here
typedef uint64_t undefined6; // Ghidra's own type is 6 bytes; widened here
typedef uint64_t undefined7; // Ghidra's own type is 7 bytes; widened here
typedef uint64_t undefined8;

typedef unsigned char byte;
typedef signed char sbyte;
typedef unsigned char uchar;
typedef unsigned short ushort;
typedef unsigned int uint;
typedef unsigned long long ulonglong;
typedef long long longlong;

// Ghidra's type for "this address holds executable code" -- almost
// always seen only as `code *`, i.e. an opaque function pointer.
typedef void code;

// Calling-convention keyword from Ghidra's x86-32 heritage; x86-64 has
// exactly one calling convention, so this is a no-op here.
#define __thiscall

// Ghidra names a CONCATxy the same way regardless of the specific
// binary: x and y are the byte widths of the high and low halves being
// joined into one wider value.
static inline uint64_t CONCAT44(uint32_t hi, uint32_t lo) {
    return (static_cast<uint64_t>(hi) << 32) | lo;
}
"#;
