/// Filename the compatibility header is written under in
/// `<project>/recovered/include/` and the name every generated header
/// includes it by.
pub const GHIDRA_COMPAT_HEADER_NAME: &str = "ghidra_compat.hpp";

/// Ghidra's decompiler output uses its own placeholder types and a
/// handful of intrinsic-looking helper functions that exist only inside
/// Ghidra itself -- `undefined`, `CONCAT44`, etc. Without declaring them
/// somewhere, every recovered file that so much as mentions an
/// unresolved-type field or return value fails to parse at all. This is
/// a real, verified-by-compiling shim: it was built by actually running
/// g++ against the Snake fixture's recovered output and adding exactly
/// what its errors named (`undefined`/`undefined4`/`undefined8`, `uint`,
/// `ulonglong`, `code`, `__thiscall`) plus `undefined`'s other standard
/// widths and Ghidra's other common short-integer aliases, which are
/// conventional across Ghidra output generally even though this specific
/// binary didn't happen to use them.
const GHIDRA_COMPAT_HEADER_BASE: &str = r#"// Generated by Debura. Declares Ghidra's own placeholder types and
// decompiler intrinsics so recovered output that still contains them
// (an address whose real type Ghidra couldn't infer, a width-combining
// operation the decompiler introduced) at least parses -- it does not
// make the *values* correct, only the syntax valid.
#pragma once
#include <cstdint>
#include <cstdlib>
#include <cstring>
#include <iostream>
#include <sstream>
#include <string>
#include <new>

// A real compile of a MinGW-targeted binary's decompiled output showed
// calls into the C runtime's own startup/threading internals
// (HeapAlloc, EnterCriticalSection, CommandLineToArgvW, ...) and Windows
// types (DWORD, HANDLE, LPVOID, ...) that Debura doesn't try to recover
// as source (a real g++ build already links a working CRT/Win32 layer;
// see debura-knowledge's ClaimClass -- these are excluded from
// *recovery* itself where their own name is recognizable, but a
// statically-linked CRT startup routine can still call them from
// otherwise-ordinary-looking code this shim needs to at least parse).
#ifdef _WIN32
#include <windows.h>
#endif

// SDL2/SDL2_ttf: specific to whatever real binary this shim was last
// verified against (PROJECT.md: this file grows by compiling real
// recovered output and adding exactly what its errors named) -- a
// project that doesn't call into SDL pays only the include cost, not a
// hard dependency, since nothing here references SDL types by name.
#if __has_include(<SDL.h>)
#include <SDL.h>
#include <SDL_ttf.h>

// A real compile hit this: `SDL_iconv_string`'s real signature takes
// `const char *inbuf` (raw bytes -- iconv converts between encodings by
// byte content, the fromcode/tocode arguments say how to interpret
// them), but Ghidra's decompiled call site passes a `LPWSTR`
// (`wchar_t *`) buffer directly -- exactly what the real compiled code
// does at the ABI level (reinterpreting a UTF-16LE buffer as bytes for
// iconv), but `wchar_t *` doesn't implicitly convert to `const char *`
// in C++ (unrelated pointer types), where it does convert to `const
// void *` (any object pointer does). Overload resolution picks this one
// only when the real, exact-match `const char *` overload isn't viable
// at all, so a genuinely correct `const char *` call site elsewhere is
// unaffected.
static inline char *SDL_iconv_string(const char *tocode, const char *fromcode, const void *inbuf, size_t inbytesleft) {
    return ::SDL_iconv_string(tocode, fromcode, static_cast<const char *>(inbuf), inbytesleft);
}
#endif

// Ghidra's own spelling for the four overridable allocation functions --
// seen in decompiled `new`/`delete` call sites as ordinary function
// calls rather than the real operators, since Ghidra's decompiler
// doesn't render operator-call syntax. Real, observed shape: only the
// non-placement, non-array-vs-scalar-typed forms have shown up so far.
static inline void *operator_new(size_t size) { return ::operator new(size); }
static inline void *operator_new__(size_t size) { return ::operator new[](size); }
static inline void operator_delete(void *ptr) { ::operator delete(ptr); }
static inline void operator_delete__(void *ptr) { ::operator delete[](ptr); }

typedef uint8_t undefined;
typedef uint8_t undefined1;
typedef uint16_t undefined2;
typedef uint32_t undefined3; // Ghidra's own type is 3 bytes; widened here
typedef uint32_t undefined4;
typedef uint64_t undefined5; // Ghidra's own type is 5 bytes; widened here
typedef uint64_t undefined6; // Ghidra's own type is 6 bytes; widened here
typedef uint64_t undefined7; // Ghidra's own type is 7 bytes; widened here
typedef uint64_t undefined8;

typedef unsigned char byte;
typedef signed char sbyte;
typedef unsigned char uchar;
typedef unsigned short ushort;
typedef unsigned short word;
typedef unsigned int uint;
typedef unsigned long long ulonglong;
typedef long long longlong;

// Ghidra's type for "this address holds executable code" -- `code *` is
// meant to *be* a callable function pointer (a real run had
// `(**(code **)ptr)(0,2,0);`, calling straight through a double
// dereference with no further cast), not a `void *`: a real compile
// showed `typedef void code;` fails exactly that call ("'code*' {aka
// 'void*'} is not a pointer-to-object type") since you can never call
// through a `void *`. A variadic function type has no such problem --
// `code *` becomes a genuine (if signature-erased) function pointer,
// callable with whatever arguments a given call site actually passes.
typedef void code(...);

// Ghidra's own marker for an x86 LOCK-prefixed instruction boundary in
// a compare-and-swap-style atomic sequence it couldn't fully decompile
// into a real C++ atomic op (seen bracketing MinGW's thread-safe CRT
// initialization). No-ops here lose the real atomicity, but that's a
// CRT-internal path, not application logic Debura is trying to recover
// faithfully.
static inline void LOCK() {}
static inline void UNLOCK() {}

// A real compile showed Ghidra's own signature/decompilation text names
// these STL types bare -- neither `std::`-qualified nor carrying their
// real template arguments (`allocator`, not `std::allocator<char>`;
// `basic_ostream`, not `std::basic_ostream<char, std::char_traits<char>>`)
// -- since Ghidra's type recovery for library templates is partial. Real
// aliases, not placeholders: each names the one instantiation that
// actually shows up in practice (`char`-based, the only one MinGW
// libstdc++ output has needed here so far).
using allocator = std::allocator<char>;
using basic_string = std::basic_string<char, std::char_traits<char>, std::allocator<char>>;
using basic_ostream = std::basic_ostream<char, std::char_traits<char>>;
using basic_stringstream =
    std::basic_stringstream<char, std::char_traits<char>, std::allocator<char>>;

// A real compile showed the *next* layer of the same problem: Ghidra's
// decompiler represents a C++ reference parameter as a raw pointer at
// the ABI level (a reference genuinely is one, in generated code), so
// `std::cout << x` -- whose real operator<< takes `ostream&` -- decompiles
// as `std::operator<<(&cout, x)`, a call shape the real (reference-taking)
// overloads don't match at all, and can't be fixed by declaring a
// pointer-taking operator<< overload either: C++ requires a non-member
// operator<< to have at least one parameter of class/enum/reference
// type, and `(ostream *, T *)` never satisfies that regardless of what
// T is (confirmed: a real compile flagged it as a hard error even
// wrapped in an unrelated template, since neither parameter's type
// actually depends on the template parameter). Ordinary functions carry
// no such restriction, so `render.rs`'s `patch_known_idioms` rewrites
// `std::operator<<(` (and `std::endl<...>(`) to call these instead --
// the `basic_string *` overload is listed ahead of (and is more
// specialized than) the generic `const Rhs &` one specifically so a
// real `basic_string` argument gets printed by content, not as a raw
// pointer value, per C++'s own partial-ordering rule for overload
// resolution.
inline ::basic_ostream *debura_stream_output(::basic_ostream *os, ::basic_string *rhs) {
    *os << *rhs;
    return os;
}
template <typename Rhs>
inline ::basic_ostream *debura_stream_output(::basic_ostream *os, const Rhs &rhs) {
    *os << rhs;
    return os;
}
inline ::basic_ostream *debura_stream_endl(::basic_ostream *os) {
    *os << std::endl;
    return os;
}

// The *other* half of the same chained-manipulator idiom
// (`std::cout << msg << std::endl;`): the outer `operator<<` -- the
// overload that accepts a manipulator function pointer, which really is
// a *member* of basic_ostream in the real ABI, unlike the free-function
// overloads for ordinary values -- decompiles as a qualified call to
// `std::basic_ostream<char,std::char_traits<char>>::operator<<`, not
// `std::operator<<`. `render.rs`'s `patch_known_idioms` rewrites that
// call to this instead, so it isn't limited to `std::endl` specifically.
using StreamManip = ::basic_ostream *(*)(::basic_ostream *);
inline ::basic_ostream *debura_stream_manip(::basic_ostream *os, StreamManip manip) {
    return manip(os);
}
// Ghidra's own auto-generated name for the *function type* (not a
// pointer to it) shaped `basic_ostream *(basic_ostream *)` -- Ghidra's
// own cast syntax at the real call site appends its own `*`
// (`(_func_..._ptr *)value`, the same way a real C function-type typedef
// is turned into a pointer), so declaring this one pointer level too
// deep made the cast produce a pointer-to-function-pointer instead of a
// plain one -- a real compile caught the resulting type mismatch.
using _func_basic_ostream_ptr_basic_ostream_ptr = ::basic_ostream *(::basic_ostream *);

// Calling-convention keyword from Ghidra's x86-32 heritage; x86-64 has
// exactly one calling convention, so this is a no-op here.
#define __thiscall
"#;

fn uint_type(bytes: u32) -> &'static str {
    match bytes {
        1 => "uint8_t",
        2 => "uint16_t",
        3 | 4 => "uint32_t",
        _ => "uint64_t",
    }
}

fn int_type(bytes: u32) -> &'static str {
    match bytes {
        1 => "int8_t",
        2 => "int16_t",
        3 | 4 => "int32_t",
        _ => "int64_t",
    }
}

/// Parses a Ghidra intrinsic name's own encoded byte widths -- the
/// naming convention `CONCATxy`/`SUBxy`/`ZEXTxy`/`SEXTxy` share: `x` and
/// `y` are always exactly one digit each (Ghidra only ever combines/
/// splits widths up to 8 bytes), so `name` matches `prefix` followed by
/// exactly two ASCII digits or it isn't one of these intrinsics at all.
fn parse_widths<'a>(name: &'a str, prefix: &str) -> Option<(u32, u32)> {
    let digits = name.strip_prefix(prefix)?;
    let mut chars = digits.chars();
    let (Some(x), Some(y), None) = (chars.next(), chars.next(), chars.next()) else {
        return None;
    };
    Some((x.to_digit(10)?, y.to_digit(10)?))
}

/// Generates exactly the `CONCAT`/`SUB`/`ZEXT`/`SEXT` intrinsic
/// definitions a recovered program actually references, from Ghidra's
/// own naming convention rather than a hardcoded, ever-growing list of
/// specific widths (PROJECT.md M15: "table-driven so the next intrinsic
/// doesn't require another ad hoc patch"). All four share one real
/// meaning regardless of which specific widths a binary happens to use:
/// `CONCATxy(hi, lo)` joins an `x`-byte high half and `y`-byte low half
/// into one `x+y`-byte value; `SUBxy(value, byteOffset)` extracts `y`
/// bytes from an `x`-byte value at a given byte offset (Ghidra always
/// calls it with a compile-time-constant offset); `ZEXTxy`/`SEXTxy`
/// zero-/sign-extend an `x`-byte value to `y` bytes.
pub fn render_ghidra_intrinsics(names: &[String]) -> String {
    let mut out = String::new();
    for name in names {
        if let Some((x, y)) = parse_widths(name, "CONCAT") {
            let (hi_ty, lo_ty, out_ty) = (uint_type(x), uint_type(y), uint_type(x + y));
            out.push_str(&format!(
                "static inline {out_ty} {name}({hi_ty} hi, {lo_ty} lo) {{ return (({out_ty})hi << {shift}) | ({out_ty})lo; }}\n",
                shift = y * 8
            ));
        } else if let Some((x, y)) = parse_widths(name, "SUB") {
            let (in_ty, out_ty) = (uint_type(x), uint_type(y));
            out.push_str(&format!(
                "static inline {out_ty} {name}({in_ty} value, int byteOffset) {{ return ({out_ty})(value >> (byteOffset * 8)); }}\n"
            ));
        } else if let Some((x, y)) = parse_widths(name, "ZEXT") {
            let (in_ty, out_ty) = (uint_type(x), uint_type(y));
            out.push_str(&format!(
                "static inline {out_ty} {name}({in_ty} value) {{ return ({out_ty})value; }}\n"
            ));
        } else if let Some((x, y)) = parse_widths(name, "SEXT") {
            let (in_ty, out_ty) = (int_type(x), int_type(y));
            out.push_str(&format!(
                "static inline {out_ty} {name}({in_ty} value) {{ return ({out_ty})value; }}\n"
            ));
        }
    }
    out
}

/// The full compatibility header: the fixed base plus exactly the
/// intrinsic definitions this program's own recovered bodies reference.
pub fn render_ghidra_compat_header(intrinsics: &[String]) -> String {
    let mut out = GHIDRA_COMPAT_HEADER_BASE.to_string();
    let generated = render_ghidra_intrinsics(intrinsics);
    if !generated.is_empty() {
        out.push_str("\n// Table-driven Ghidra CONCAT/SUB/ZEXT/SEXT intrinsics this program's\n");
        out.push_str("// own recovered bodies actually reference.\n");
        out.push_str(&generated);
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generates_only_the_intrinsics_actually_referenced() {
        let header = render_ghidra_compat_header(&[
            "CONCAT44".to_string(),
            "CONCAT71".to_string(),
            "SUB84".to_string(),
            "ZEXT48".to_string(),
            "SEXT14".to_string(),
        ]);
        assert!(header.contains("uint64_t CONCAT44(uint32_t hi, uint32_t lo)"), "{header}");
        assert!(header.contains("uint64_t CONCAT71(uint64_t hi, uint8_t lo)"), "{header}");
        assert!(header.contains("uint32_t SUB84(uint64_t value, int byteOffset)"), "{header}");
        assert!(header.contains("uint64_t ZEXT48(uint32_t value)"), "{header}");
        assert!(header.contains("int32_t SEXT14(int8_t value)"), "{header}");
        assert!(!header.contains("CONCAT62"), "must not generate an intrinsic nothing referenced");
    }

    #[test]
    fn unrecognized_names_are_silently_skipped() {
        let header = render_ghidra_intrinsics(&["NOT_AN_INTRINSIC".to_string(), "CONCATxy".to_string()]);
        assert!(header.is_empty(), "{header}");
    }
}
