/// Filename the per-program Ghidra data-symbol declarations are written
/// under, and the name every generated `.cpp` includes it by. Always
/// written, even with zero symbols, so the unconditional `#include`
/// every generated source file carries always resolves.
pub const GHIDRA_SYMBOLS_HEADER_NAME: &str = "ghidra_symbols.hpp";

/// Declares `extern` placeholders for every `DAT_*`/`PTR_*`/`_refptr_*`
/// name a recovered body references, so the symbol at least resolves.
/// The real type (and value) at that address isn't known, and restoring
/// it needs real data extraction from Ghidra that doesn't exist yet --
/// this only makes the *name* usable. A generic byte works for `DAT_*`/
/// `PTR_*` (an arithmetic operand implicitly converts from a byte the
/// same as any other numeric type; a vtable-pointer-slot assignment
/// pattern gets an explicit cast inserted at the call site instead of
/// needing the exact pointer type here, see `patch_known_idioms`), but
/// `_refptr_*` specifically means "a synthesized pointer to a relocated
/// global" in Ghidra's own naming convention, and is always seen
/// *dereferenced* (`*_refptr_...`) -- a real compile confirmed a plain
/// byte there fails with "invalid type argument of unary '*'", so this
/// one family needs to be declared as a pointer.
pub fn render_ghidra_symbols_header(symbols: &[String]) -> String {
    let mut out = String::new();
    out.push_str("// Generated by Debura. Placeholder declarations for Ghidra's own\n");
    out.push_str("// auto-named data symbols referenced in recovered bodies -- see\n");
    out.push_str("// each name's own address in the original binary for its real value.\n");
    out.push_str("#pragma once\n\n");
    for symbol in symbols {
        if symbol.starts_with("_refptr_") {
            out.push_str(&format!("extern unsigned char *{symbol};\n"));
        } else {
            out.push_str(&format!("extern unsigned char {symbol};\n"));
        }
    }
    out
}
