use crate::compat::GHIDRA_COMPAT_HEADER_NAME;
use crate::data_symbols::{DataResolution, DataSymbolKind};

/// Filename the per-program Ghidra data-symbol declarations are written
/// under, and the name every generated `.cpp` includes it by. Always
/// written, even with zero symbols, so the unconditional `#include`
/// every generated source file carries always resolves.
pub const GHIDRA_SYMBOLS_HEADER_NAME: &str = "ghidra_symbols.hpp";

/// Declares `extern` placeholders for every `DAT_*`/`PTR_*`/`_refptr_*`
/// name a recovered body references, so the symbol at least resolves.
/// The real type (and value) at that address isn't known, and restoring
/// it needs real data extraction from Ghidra that doesn't exist yet --
/// this only makes the *name* usable. A generic byte works for `DAT_*`
/// (an arithmetic operand implicitly converts from a byte the same as
/// any other numeric type; a vtable-pointer-slot assignment pattern gets
/// an explicit cast inserted at the call site instead of needing the
/// exact pointer type here, see `patch_known_idioms`), but `PTR_*` and
/// `_refptr_*` both specifically mean "this address holds a pointer" in
/// Ghidra's own naming convention (a plain data byte doesn't), and both
/// are seen *dereferenced* (`*PTR_DAT_...`, `*_refptr_...`) -- a real
/// compile confirmed a plain byte there fails two different ways
/// (`_refptr_*`: "invalid type argument of unary '*'"; `PTR_*`, same
/// error, found later against a different real body), so both families
/// need to be declared as pointers.
/// `unresolved_calls` are call-site names (`FUN_x`, `thunk_FUN_x`) M15's
/// symbol-resolution pass (`symtab.rs`) couldn't match to any recovered
/// class method or standalone function -- Debura found no definition for
/// them at all, not even that they're a method of some unnamed class.
/// Declaring each as a permissive, fully-variadic prototype (`long long
/// name(...);`, valid C++ for "accepts any arguments") is the same
/// graceful-degradation PROJECT.md M15 asks for: a real but generic
/// prototype that at least compiles, rather than a hard error, and
/// rather than guessing a wrong specific signature. This only makes the
/// call sites *parse* -- nothing defines these functions, so a real
/// link step still needs a definition from somewhere before the program
/// can actually run.
/// PROJECT.md M15: "declarations should be generated from the same
/// global symbol table as definitions -- then cross-file visibility
/// becomes automatic." A real compile confirmed why standalone functions
/// specifically needed this: every recovered free function is defined in
/// one shared `functions.cpp`, sorted by address -- so a call from an
/// earlier-address function to a later-address one failed to compile for
/// ordinary C++ forward-declaration reasons, and a call *into*
/// `functions.cpp` from a class's own `.cpp` had no declaration visible
/// at all. Declaring every one of them here, in the header every
/// generated source file already includes unconditionally, fixes both
/// at once. Class methods don't need the same treatment: they're already
/// declared in their own class's header, which every caller already
/// `#include`s via `references`.
pub fn render_function_declarations(functions: &[(String, String, String)]) -> String {
    let mut out = String::new();
    for (return_type, name, params) in functions {
        out.push_str(&format!("{return_type} {name}({params});\n"));
    }
    out
}

pub fn render_ghidra_symbols_header(
    symbols: &[String],
    unresolved_calls: &[String],
    function_declarations: &str,
) -> String {
    render_ghidra_symbols_header_resolved(symbols, &[], unresolved_calls, function_declarations)
}

/// Same as `render_ghidra_symbols_header`, but real evidence (PROJECT.md
/// M18.2's `DataResolution`) can upgrade a symbol from a bare `extern`
/// placeholder to a genuine definition -- a real captured constant's
/// exact bytes, a real vtable slot's function pointer, ... `resolutions`
/// is looked up by symbol name; anything in `symbols` with no matching
/// resolution (or an `UnknownData`/`CodeAddressAlias`/`RuntimeData`/
/// `ExternalGlobalAlias` one -- none of which this pass fabricates a
/// definition for, see `DataSymbolKind`'s own doc comments) falls back to
/// the exact same bare-`extern` behavior as before this module existed.
pub fn render_ghidra_symbols_header_resolved(
    symbols: &[String],
    resolutions: &[DataResolution],
    unresolved_calls: &[String],
    function_declarations: &str,
) -> String {
    let mut out = String::new();
    out.push_str("// Generated by Debura. Declarations (and, where PROJECT.md M18.2's\n");
    out.push_str("// evidence supports one, real definitions) for Ghidra's own\n");
    out.push_str("// auto-named data symbols referenced in recovered bodies.\n");
    out.push_str("#pragma once\n\n");
    // Self-sufficient regardless of include order: `render_source`
    // includes this header *before* the class's own header (the thing
    // that otherwise pulls in ghidra_compat.hpp), and the function
    // declarations below use its types (`undefined8`, `longlong`, ...).
    // A real compile hit exactly this -- 900+ "'undefined' does not name
    // a type" errors -- before this include was added here directly.
    out.push_str(&format!("#include \"{GHIDRA_COMPAT_HEADER_NAME}\"\n\n"));
    if !function_declarations.is_empty() {
        out.push_str("// Every recovered standalone function, forward-declared here so any\n");
        out.push_str("// file that includes this header (all of them do) can call any of\n");
        out.push_str("// them regardless of definition order.\n");
        out.push_str(function_declarations);
        out.push('\n');
    }
    for symbol in symbols {
        let resolution = resolutions.iter().find(|r| &r.symbol_name == symbol);
        match resolution.map(|r| &r.kind) {
            Some(DataSymbolKind::ConstantData { size, bytes }) => {
                out.push_str(&render_byte_array_definition(symbol, *size, bytes, true));
            }
            Some(DataSymbolKind::MutableStaticData { size, bytes }) => {
                out.push_str(&render_byte_array_definition(symbol, *size, bytes, false));
            }
            Some(DataSymbolKind::FunctionPointerAlias { target_function }) => {
                out.push_str(&format!("void *{symbol} = (void *)&{target_function};\n"));
            }
            Some(DataSymbolKind::VtableData { slot0_target: Some(target), .. }) => {
                out.push_str(&format!("void *{symbol} = (void *)&{target};\n"));
            }
            // `VtableData` with no safe function-pointer representation
            // (a Method/Constructor/Destructor target -- see
            // `classify_data_symbol`'s own doc comment), and every other
            // kind this pass doesn't fabricate a definition for
            // (`ExternalGlobalAlias`, `RuntimeData`, `CodeAddressAlias`,
            // `UnknownData`), or no resolution at all: the same bare
            // `extern` placeholder as before M18.2 existed.
            _ => {
                if symbol.starts_with("_refptr_") || symbol.starts_with("PTR_") {
                    out.push_str(&format!("extern unsigned char *{symbol};\n"));
                } else {
                    out.push_str(&format!("extern unsigned char {symbol};\n"));
                }
            }
        }
    }
    if !unresolved_calls.is_empty() {
        out.push_str("\n// Call targets M15's symbol resolution pass found no recovered\n");
        out.push_str("// definition for at all -- not a class method, not a standalone\n");
        out.push_str("// function. Fully variadic so any call shape parses; still needs a\n");
        out.push_str("// real definition from somewhere before the program can link.\n");
        for name in unresolved_calls {
            out.push_str(&format!("long long {name}(...);\n"));
        }
    }
    out
}

/// `unsigned char NAME[SIZE] = {0x.., ...};` (or `const unsigned char`
/// for read-only data) -- the exact captured bytes, never interpreted as
/// any specific numeric/struct type Debura doesn't have real evidence
/// for (PROJECT.md M18.2: "Unknown is better than confidently wrong"
/// applies to a global's own C++ type the same way it already applies to
/// semantic naming). A real call site that needs a specific type
/// (`*(double *)&DAT_x`) already does its own reinterpreting cast --
/// this only needs to supply real storage of the right size and content,
/// not the exact type a specific use site happens to want.
fn render_byte_array_definition(symbol: &str, size: u64, bytes: &[u8], readonly: bool) -> String {
    let qualifier = if readonly { "const " } else { "" };
    let byte_list: Vec<String> = bytes.iter().map(|b| format!("0x{b:02x}")).collect();
    format!("{qualifier}unsigned char {symbol}[{size}] = {{{}}};\n", byte_list.join(","))
}
